"""add date of registration

Revision ID: 431005dd2c6f
Revises: da0518dd80ec
Create Date: 2024-04-17 20:15:32.448464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431005dd2c6f'
down_revision = 'da0518dd80ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_registration', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_of_registration')

    # ### end Alembic commands ###
