"""add migration

Revision ID: 65828d0f3b9c
Revises: bc5f414294b1
Create Date: 2024-04-16 22:56:43.218447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65828d0f3b9c'
down_revision = 'bc5f414294b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achivement', schema=None) as batch_op:
        batch_op.drop_index('ix_achivement_user_id')

    op.drop_table('achivement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achivement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('distance', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='achivement_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='achivement_pkey')
    )
    with op.batch_alter_table('achivement', schema=None) as batch_op:
        batch_op.create_index('ix_achivement_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
