"""?? achivement

Revision ID: 899ff26ac5f0
Revises: 65828d0f3b9c
Create Date: 2024-04-16 23:06:00.504035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899ff26ac5f0'
down_revision = '65828d0f3b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
