"""add achivements

Revision ID: 959fb1556c3a
Revises: d1e1561c62cc
Create Date: 2024-04-16 20:11:42.044707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959fb1556c3a'
down_revision = 'd1e1561c62cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achivements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achivements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achivements_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achivements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achivements_user_id'))

    op.drop_table('achivements')
    # ### end Alembic commands ###
