"""fixed achievements 2.0

Revision ID: b00d84772bec
Revises: 899ff26ac5f0
Create Date: 2024-04-16 23:10:54.581706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00d84772bec'
down_revision = '899ff26ac5f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
