"""admin_premium deleted

Revision ID: bbeffa56587a
Revises: 0bfd50757b47
Create Date: 2024-05-08 00:44:34.897703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbeffa56587a'
down_revision = '0bfd50757b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin__premium')
    with op.batch_alter_table('admin__user', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=postgresql.ENUM('BLOCK', 'UNBLOCK', name='adminuseraction'),
               type_=sa.Enum('BLOCK', 'UNBLOCK', 'GRANT_PREMIUM', 'REVOKE_PREMIUM', name='adminaction'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin__user', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.Enum('BLOCK', 'UNBLOCK', 'GRANT_PREMIUM', 'REVOKE_PREMIUM', name='adminaction'),
               type_=postgresql.ENUM('BLOCK', 'UNBLOCK', name='adminuseraction'),
               existing_nullable=False)

    op.create_table('admin__premium',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('premium_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', postgresql.ENUM('GRANT_PREMIUM', 'REVOKE_PREMIUM', name='adminpremiumaction'), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name='admin__premium_admin_id_fkey'),
    sa.ForeignKeyConstraint(['premium_id'], ['premium.id'], name='admin__premium_premium_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='admin__premium_pkey')
    )
    # ### end Alembic commands ###
