"""rename achivement

Revision ID: bc5f414294b1
Revises: 959fb1556c3a
Create Date: 2024-04-16 20:23:19.788889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5f414294b1'
down_revision = '959fb1556c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achivement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achivement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achivement_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('achivements', schema=None) as batch_op:
        batch_op.drop_index('ix_achivements_user_id')

    op.drop_table('achivements')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achivements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('distance', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='achivements_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='achivements_pkey')
    )
    with op.batch_alter_table('achivements', schema=None) as batch_op:
        batch_op.create_index('ix_achivements_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('achivement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achivement_user_id'))

    op.drop_table('achivement')
    # ### end Alembic commands ###
