"""delete prem-award

Revision ID: fddda835cd46
Revises: 5b49a2ba4df5
Create Date: 2024-05-03 23:39:19.569784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fddda835cd46'
down_revision = '5b49a2ba4df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('premium__award')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('premium__award',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='premium__award_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='premium__award_pkey')
    )
    # ### end Alembic commands ###
